image: ubuntu

#install:
#  - add2path_suffix /opt/octopus
#  - curl -L "https://download.octopusdeploy.com/octopus-tools/6.2.3/OctopusTools.6.2.3.ubuntu.16.04-x64.tar.gz" -o OctopusTools.tar.gz
#  - mkdir octopus && tar zxf OctopusTools.tar.gz -C octopus
init:
  - appveyor version
  - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

test_script:
  - Octo
  - Octo version

build: off
