image: ubuntu

install:
  - curl -L "https://download.octopusdeploy.com/octopus-tools/6.2.3/OctopusTools.6.2.3.ubuntu.16.04-x64.tar.gz" -o OctopusTools.tar.gz
  - mkdir octopus && tar zxf OctopusTools.tar.gz -C octopus
  - ./octopus/Octo
